my:
  greeting: Updated hello world from spring-boot-config server
  list:
    values: One, Two, Thres, Four, Five

db:
  connection: connection-string-here-from-configServer
  host: 127.0.0.0
  port: 1200    
